### 전체 회원 조회
GET http://localhost:8080/entity/users

### 회원 조회
GET http://localhost:8080/entity/users/4

### 신규 회원 등록 (insert)
POST http://localhost:8080/entity/users
Content-Type: application/json

{
  "id": "userTest",
  "pwd": "passTest",
  "name": "판다",
  "enrollDate": "2024-06-07"
}

### 기존 회원 수정 (update)
PUT http://localhost:8080/entity/users/4
Content-Type: application/json

{
  "id": "modifyTest",
  "pwd": "modifyTest",
  "name": "진화한 판다"
}

### 회원 삭제 (delete)
DELETE http://localhost:8080/entity/users/4